version: "3.9"
 
services:
  db:
    image: postgres:17
    container_name: kinoSystemDB-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: kinoSystemDB
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
 
  postgrest:
    image: postgrest/postgrest:v13.0.4
    container_name: kinoSystemDB-api
    restart: always
    depends_on:
      - db
    environment:
      PGRST_DB_URI: postgres://myuser:mypassword@db:5432/kinoSystemDB
      PGRST_DB_SCHEMAS: public
      PGRST_DB_ANON_ROLE: myuser
    ports:
      - "3001:3000"
 
volumes:
  db_data: